name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1" # Every monday 6 AM

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [latest, nightly]
        include:
          - os: windows-latest
            crystal: nightly
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global column.ui always
          git config --global core.autocrlf false

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run specs
        run: make test

      - name: Check formatting
        run: crystal tool format --check src spec

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Touch doc files with git timestamps because asciidoctor image has no git
        run: >
          for file in docs/*.adoc; do touch -m -d "$(git log -1 --format='%aI' -- $file)" $file; echo "$file: $(git log -1 --format='%aI' -- $file)"; done
      - name: Debug
        run: ls -l docs
      - name: Build manpages
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "make clean_docs manpages"
      - name: Check manpages are up to date
        run: "git diff --color --exit-code"
